//ACTION AUTH
export const GET_LOGIN = 'GET_LOGIN';

//ACTION ROOM
export const GET_ROOMS = 'GET_ROOMS';
export const ADD_ROOM = 'ADD_ROOM';

//ACTION CUSTOMER
export const GET_CUSTOMERS = 'GET_CUSTOMERS';
