//ACTION AUTH
export const GET_LOGIN = 'GET_LOGIN';

//ACTION ROOM
export const GET_ROOMS = 'GET_ROOMS';
export const ADD_ROOM = 'ADD_ROOM';
export const UPDATE_ROOM = 'UPDATE_ROOM';

//ACTION CUSTOMER
export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';

//ACTION ORDER
export const GET_ORDERS = 'GET_ORDERS';
